### ISSUE TITLE
Testing, CI?

### ISSUE THREAD

**Issue by EivindArvesen** [eivind88/prm#11]
It would be great to have some sort of testing, so that contributors don't have to manually perform every action/combination that could be affected by their changes, or worse yet, don't test at all.

It would probably be best to set up integration with [Travis CI](https://travis-ci.org), or something, but I have no idea what options exist for testing with `bash` and `zsh` – except for [shUnit2](https://github.com/kward/shunit2), which I recently stumbled upon.

**Comment by stanimirovv** [comment]
I will look into writing some basic tests. Should they be in bash or is perl/python fine too ?

**Comment by EivindArvesen** [comment]
That would be great!
I would prefer `bash` or `python`.

On the one hand, keeping everything in the same language would be tidy (and ensure that contributors can deal with all parts), but on the other hand `python` has some well established frameworks.

What are your thoughts?
And what approach were you thinking of?

**Comment by stanimirovv** [comment]
It makes sense to keep them in bash, at least for now.
The approach I am thinking of is:
1) Keep all the tests divided logically into files (for example one file that tests start, one file that tests stop, one file that tests the environment variables and so on)
2) Have a script that will run all of the files containing the tests.

How does it sound ?

**Comment by EivindArvesen** [comment]
It sounds great!

Don't be afraid to make commits and PRs often with regards to this issue, though.
It looks like I'll have some spare time this weekend, so I might have time to help out with this after fixing some other issues, if you'd like.

**Comment by EivindArvesen** [comment]
@IamBc : What is your current status on this?
I'm thinking about dedicating some time to writing tests over the weekend.

**Comment by stanimirovv** [comment]
Sorry for the delay, I was caught up with some personal issues. I am going to write some tests to start things up tonight. I will make the pull request either tonight or Saturday morning latest.

**Comment by stanimirovv** [comment]
I am very sorry, but my contributions will be delayed indefinitely. I will try to keep up with the progress of the project and at least try to give feedback on the new features.

**Comment by EivindArvesen** [comment]
No problem at all. I hope things work out.
I will certainly appreciate any feedback!

**Comment by EivindArvesen** [comment]
Just started out with [shUnit2](https://shunit2.googlecode.com/svn/trunk/source/2.1/doc/shunit2.html#function-reference).

It works great, and both `bash` and `zsh` tests smoothly on my machine.
Travis CI, however, [is another story](https://travis-ci.org/eivind88/prm/builds/84424080). Here, `zsh` keeps getting an "Unknown failure" with shUnit2.

I'd be very grateful for any suggestions from someone with experience regarding `zsh` (and/or shUnit2) on Travis.

**Comment by EivindArvesen** [comment]
Migrated the tests from shUnit2 to [BATS](https://github.com/sstephenson/bats) and made a few scripts.
Things finally work. 

Testing should probably be mentioned in the wiki as well.
