### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by EivindArvesen** [eivind88/prm#12]
prm should return status codes, e.g. `return 1` upon failure.

It is very important to use `return`, as opposed to `exit`, since the latter will kill the shell (since prm is sourced).

Some relevant lines can be seen in adbf77c2de6c3a396daec39a58a57ef76346e276.

**Comment by stanimirovv** [comment]
If I understand correctly you want to put relevant return statuses where the exits used to be, right ? 
If that's the case, let's decide on some statuses and  I will add them. 
These are the ones that come to mind:
http://tldp.org/LDP/abs/html/exitcodes.html

Do you think we can use them or should we use other ones ?

**Comment by EivindArvesen** [comment]
That's right – though not exclusively at these places. Anywhere things go right or wrong, where prm implicitly returns.

Those are exactly the codes I was thinking of.

For now, I think just status codes `0` and `1` (and possibly `2`, if necessary) will do.

After tests (#11) are up and running, we can discuss possible custom codes, but I don't see any need for them as of right now.

**Comment by stanimirovv** [comment]
Okay I will add the return codes and make a pull request.
