### ISSUE TITLE
Error handling and messages

### ISSUE THREAD

**Issue by EivindArvesen** [eivind88/prm#13]
Handle some edge cases, probably needs a couple of error messages as well.
- What if files dissappear at unexpected points?
- What if users try to name project something that exists (e.g. temp-file) or is reserved or starts with dot?

Related to issue #12.

Some relevant lines can be seen in adbf77c2de6c3a396daec39a58a57ef76346e276.

**Comment by nikklassen** [comment]
I'm not sure that this belongs here, but it would be handy to warn the user if $EDITOR is empty.  It took me a while to debug the error that arises from that situation.

**Comment by EivindArvesen** [comment]
In any case, it certainly needs fixing!

**Comment by EivindArvesen** [comment]
@nikklassen : Thanks for the heads-up! Added a test to check whether `$EDITOR` is set before add, copy and edit actions.

**Comment by nikklassen** [comment]
Sweet, thanks!
