### ISSUE TITLE
Show something on bare command

### ISSUE THREAD

**Issue by davenquinn** [eivind88/prm#17]
Cool tool! I've enjoyed it so far.

From an interface perspective, I'd like to see some output when I type the bare command. Right now it's just `illegal option --`. Perhaps either print usage or a listing of active/all projects? Not sure what would be best, but it would be nice to save a few keystrokes and cue in on what to do next.

**Comment by EivindArvesen** [comment]
Thank you!

How about something like:

``` bash
prm: missing option -- (see "prm --help" for help)
usage: prm <option> [<args>] ...
```

, or do you mean it should print the help-screen ([`--help`](https://github.com/eivind88/prm#usage))?

**Comment by davenquinn** [comment]
I'd love to see it print the help screen by default. If I type the bare command, I'd like a reminder of what to do next. Alternatively, it could print a brief status, such as

```
2 of 52 projects active:
  2315      Naukluft
  1132      widget-thingum
see "prm --help" for help
```

This would be especially useful to have three keystrokes away at all times...

**Comment by EivindArvesen** [comment]
Bare command now prints help screen.
