### ISSUE TITLE
Editing start/stop scripts is broken on Cygwin

### ISSUE THREAD

**Issue by FredDeschenes** [eivind88/prm#36]
This relates to PR https://github.com/eivind88/prm/issues/27, which introduced a check with "uname" to use the "cygpath" executable when opening the scripts. This works fine when using an editor external to Cygwin (ex: Sublime Text), but editors installed in Cygwin (ex: vim) will most likely not be able to open a file with a native Windows path.

I've made PR https://github.com/eivind88/prm/pull/35 to make the usage of "cygpath" optional.

**Comment by EivindArvesen** [comment]
By the way, @FredDeschenes , could you send me an email at the address on my profile?

**Comment by FredDeschenes** [comment]
Yup, email incoming!
