### ISSUE TITLE
Making the prm project path a configuration parameter

### ISSUE THREAD

**Issue by stanimirovv** [eivind88/prm#9]
Currently the only possible project path is $HOME/.prm/
which means that if I want to use prm for my projects I must
1) Obey it's structure and move my projects there
2) Edit the source of prn and set it to my project directory

The latter isn't a solution since if I have for example several directories with projects (for example work and personal)
It won't work.

I suggest to make the path based on an enviroment variable and fallback to the default path only if it isn't set.
That should solve the described problem above. If this makes scence to you and you agree please say so. I will make a 
pull request with the edit.

**Comment by EivindArvesen** [comment]
Just to be clear here: you are talking about (what results in) a sort of categorization within prm, to keep work and personal projects separated in prm itself – _not_ about where you place your own source code, right?

Basing prm's data-path on an environment variable sounds like a good idea, regardless.

**Comment by stanimirovv** [comment]
Yes, I am talking about a categorization within prm.
I will make a pull request with the parameterized path. The thing that should be decided before that though is the name of the env variable. 

The first thing which comes to my mind is:
PRM_PATH

and if it isn't set, then it will default to the current value:   $HOME/.prm/
That way we will keep compatibility and there will be a default setting. 
Thoughts ?

**Comment by EivindArvesen** [comment]
Good.

Sounds great – it's precisely what came to my mind as well.
